# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\"\n\nNumberPair\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x9b\x02\n\nCalculator\x12\x34\n\nSquareRoot\x12\x12.calculator.Number\x1a\x12.calculator.Number\x12\x31\n\x03\x41\x64\x64\x12\x16.calculator.NumberPair\x1a\x12.calculator.Number\x12\x36\n\x08Subtract\x12\x16.calculator.NumberPair\x1a\x12.calculator.Number\x12\x36\n\x08Multiply\x12\x16.calculator.NumberPair\x1a\x12.calculator.Number\x12\x34\n\x06\x44ivide\x12\x16.calculator.NumberPair\x1a\x12.calculator.Numberb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NUMBERPAIR']._serialized_start=32
  _globals['_NUMBERPAIR']._serialized_end=66
  _globals['_NUMBER']._serialized_start=68
  _globals['_NUMBER']._serialized_end=91
  _globals['_CALCULATOR']._serialized_start=94
  _globals['_CALCULATOR']._serialized_end=377
# @@protoc_insertion_point(module_scope)
